# Generated by Django 3.0.6 on 2020-05-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HosptialSIte', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='ResourceDetails',
        ),
    ]
